<a href="https://colab.research.google.com/github/bedirhansahin/pytorch-notes/blob/main/PyTorchFundementals.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
!pip uninstall torch -y

Found existing installation: torch 2.1.0+cu118
Uninstalling torch-2.1.0+cu118:
  Successfully uninstalled torch-2.1.0+cu118


In [ ]:
!pip3 install torch==1.11.0

     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 750.6/750.6 MB 2.3 MB/s eta 0:00:00
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
torchaudio 2.1.0+cu118 requires torch==2.1.0, but you have torch 1.11.0 which is incompatible.
torchdata 0.7.0 requires torch==2.1.0, but you have torch 1.11.0 which is incompatible.
torchtext 0.16.0 requires torch==2.1.0, but you have torch 1.11.0 which is incompatible.
torchvision 0.16.0+cu118 requires torch==2.1.0, but you have torch 1.11.0 which is incompatible.


In [ ]:
import torch
print(torch.__version__)

1.11.0+cu102


### SCALAR

In [ ]:
scalar = torch.tensor(7)
scalar.ndim

0

In [ ]:
scalar.item()

7

### VECTOR

In [ ]:
vector = torch.tensor([7, 7])
vector.ndim

1

In [ ]:
vector.shape

torch.Size([2])

### MATRIX

In [ ]:
MATRIX = torch.tensor(
    [
        [1, 2, 3],
        [4, 5, 6],
        [7, 8, 9],
    ]
    )

In [ ]:
MATRIX.ndim

2

In [ ]:
MATRIX.shape

torch.Size([3, 3])

In [ ]:
MATRIX[0]

tensor([1, 2, 3])

In [ ]:
MATRIX[0][2]

tensor(3)

### TENSOR

In [ ]:
# first square brackets => dim = 0
# second square brackets => dim = 1
# third square brackets => dim = 2

TENSOR = torch.tensor(
    [
        # First tensor
        [
            [1, 2, 3],
            [4, 5, 6],
            [7, 8, 9]
        ],
        # Second tensor
        [
            [0, 0, 0],
            [0, 0, 0],
            [0, 0, 0]
        ]
    ]
)
TENSOR

tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]],

        [[0, 0, 0],
         [0, 0, 0],
         [0, 0, 0]]])

In [ ]:
TENSOR.ndim

3

In [ ]:
TENSOR.shape

torch.Size([2, 3, 3])

In [ ]:
TENSOR[0]

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [ ]:
TENSOR[0][0]

tensor([1, 2, 3])

In [ ]:
TENSOR[0][0][0]

tensor(1)

### CREATE RANDOM TENSOR

Why random tensors?

Random tensors are importan because the way many neural networks learn is that they start with tensors full of random numbers and then adjust those random numbers to better represent the data.
`Start with random numbers -> look at data -> update random numbers -> look at data -> update random numbers`

In [ ]:
# RANDOM_TENSOR = torch.rand(2, 8, 8)
RANDOM_TENSOR = torch.rand(3, 4)
print(RANDOM_TENSOR)
print(f"dimension: {RANDOM_TENSOR.ndim}")

tensor([[0.2480, 0.2972, 0.0342, 0.0583],
        [0.3407, 0.8257, 0.7523, 0.4255],
        [0.5769, 0.1585, 0.0435, 0.7411]])
dimension: 2


In [ ]:
# Create a random tensor with similar shape to an image tensor
RANDOM_IMAGE_SIZE_TENSOR = torch.rand(size=(3, 224, 224)) # color_channels, height, width
RANDOM_IMAGE_SIZE_TENSOR.shape, RANDOM_IMAGE_SIZE_TENSOR.ndim

(torch.Size([3, 224, 224]), 3)

### ZEROS AND ONES

In [ ]:
zeros = torch.zeros(size=(3, 4))
zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [ ]:
ones = torch.ones(size=(3, 4))
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [ ]:
ones.dtype

torch.float32

### CREATING A RANGE OF TENSORS AND TENSORS LIKE

In [ ]:
one_to_ten = torch.arange(start=1, end=11, step=1)
one_to_ten

tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [ ]:
ten_zeros = torch.zeros_like(input=one_to_ten)
ten_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

### TENSOR DATATYPES

**Note:** Tensor datatypes is one of the 3 big errors you will run into with PyTorch and Deep Learning:
1. Tensors not right datatypes
2. Tensors not right shape
3. Tensors not on the right device

In [ ]:
float_32_tensor = torch.tensor(
                      [3.0, 6.0, 9.0],
                      dtype=None,
                      device=None, # Cuda
                      requires_grad=False
                      )

print(float_32_tensor)
print(float_32_tensor.dtype)

tensor([3., 6., 9.])
torch.float32


In [ ]:
float_16_tensor = float_32_tensor.type(torch.float16) # torch.float16 = torch.half
float_16_tensor

tensor([3., 6., 9.], dtype=torch.float16)

In [ ]:
float_16_tensor * float_32_tensor

tensor([ 9., 36., 81.])

In [ ]:
integer_32_tensor = torch.tensor([3, 6, 9], dtype=torch.int32)
integer_32_tensor

tensor([3, 6, 9], dtype=torch.int32)

In [ ]:
integer_32_tensor * float_32_tensor

tensor([ 9., 36., 81.])

In [ ]:
some_tensor = torch.rand(3, 4)
some_tensor

tensor([[0.0713, 0.4017, 0.3644, 0.5135],
        [0.2742, 0.3651, 0.0673, 0.0424],
        [0.5932, 0.5077, 0.4038, 0.5496]])

In [ ]:
print(some_tensor)
print(f"Datatype of tensor: {some_tensor.dtype}")
print(f"Shape of tensor: {some_tensor.size()}") #  some_tensor.shape
print(f"Device of tensor: {some_tensor.device}")


tensor([[0.0713, 0.4017, 0.3644, 0.5135],
        [0.2742, 0.3651, 0.0673, 0.0424],
        [0.5932, 0.5077, 0.4038, 0.5496]])
Datatype of tensor: torch.float32
Shape of tensor: torch.Size([3, 4])
Device of tensor: cpu


### Manipulating Tensors (tensor operations)

Tensor operations include:
* Addition
* Subtraction
* Multiplication (element-wise)
* Division
* Matrix multiplication

In [ ]:
k = 3
tensorX = torch.tensor([1, 2, 3])

print(tensorX + 10)
print(tensorX - 10)
print(tensorX * 10)
print(tensorX / 10)
print(tensorX)

tensor([11, 12, 13])
tensor([-9, -8, -7])
tensor([10, 20, 30])
tensor([0.1000, 0.2000, 0.3000])
tensor([1, 2, 3])


In [ ]:
print(tensorX * k)

tensor([3, 6, 9])


In [ ]:
print(torch.add(tensorX, 100))
print(torch.subtract(tensorX, 100))
print(torch.multiply(tensorX, 100))
print(torch.divide(tensorX, 100))

tensor([101, 102, 103])
tensor([-99, -98, -97])
tensor([100, 200, 300])
tensor([0.0100, 0.0200, 0.0300])


In [ ]:
# Matrix Multiplication
tensorY = torch.tensor([5, 10, 15])
print(f"{tensorX} * {tensorY} = {tensorX * tensorY}")

tensor([1, 2, 3]) * tensor([ 5, 10, 15]) = tensor([ 5, 20, 45])


In [ ]:
%%time

value = 0

for i in range(len(tensorX)):
  value += tensorX[i] * tensorY[i]

print(value)

tensor(70)
CPU times: user 262 µs, sys: 38 µs, total: 300 µs
Wall time: 307 µs


In [ ]:
%%time
torch.matmul(tensorX, tensorY)

CPU times: user 58 µs, sys: 8 µs, total: 66 µs
Wall time: 70.1 µs


tensor(70)

In [ ]:
"""torch.matmul(torch.rand(3, 2), torch.rand(3, 2))""" # RuntimeError: mat1 and mat2 shapes cannot be multiplied (3x2 and 3x2)
torch.matmul(torch.rand(2, 3), torch.rand(3, 2)).shape

torch.Size([2, 2])

In [ ]:
# Shapes for matrix multiplication
tensorA = torch.tensor([
    [1, 2],
    [3, 4],
    [5, 6]
])
tensorB = torch.tensor([
    [7, 10],
    [8, 11],
    [9, 12]
])

In [ ]:
torch.mm(tensorA, tensorB) # mm is the same as matmul

RuntimeError: ignored

In [ ]:
"""
To fix tensor shape issues, we can manipulate the shape of one of our tensors ( Transpoze )
"""

print(tensorB.T) # transpoze
print("\n", tensorB.T.shape)

tensor([[ 7,  8,  9],
        [10, 11, 12]])

 torch.Size([2, 3])


In [ ]:
torch.mm(tensorA, tensorB.T)

tensor([[ 27,  30,  33],
        [ 61,  68,  75],
        [ 95, 106, 117]])

### TENSOR AGGREGATION
* max
* min
* mean
* sum

In [ ]:
tensorC = torch.tensor([
    [1, 5, 12],
    [-4, 6, 1],
    [7, 11, -6]
])

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

In [ ]:
print(f"Min: {torch.min(tensorC)}, {tensorC.min()}")
print(f"Max: {torch.max(tensorC)}, {tensorC.max()}")
print(f"Mean: {torch.mean(tensorC.type(torch.float32))}, {tensorC.type(torch.float32).mean()}") # Should be float for mean
print(f"Sum: {torch.sum(tensorC)}, {tensorC.sum()}")


Min: -6, -6
Max: 12, 12
Mean: 3.6666667461395264, 3.6666667461395264
Sum: 33, 33


In [ ]:
print(f"Where is min element: {tensorC.argmin()}") # as an index value
print(f"Where is max element: {tensorC.argmax()}") # as an index value

Where is min element: 8
Where is max element: 2


### RESHAPING, VIEWING, SQUEZZING AND STACKING TENSORS

In [ ]:
x = torch.arange(1., 10.)
x, x.shape

(tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.]), torch.Size([9]))

In [ ]:
"""
torch.Size([a, b]) and reshaped.Size([c, d]) =>  c * d == a * b
"""

try:
  x_reshaped = x.reshape(1, 7)
  x_reshaped, x_reshaped.shape
except RuntimeError as e:
  print("Error: ", e)

print("\n")
x_reshaped = x.reshape(1, 9)
print(x_reshaped)
print(x_reshaped.shape)

print("\n")
x_reshaped = x.reshape(3, 3)
print(x_reshaped)
print(x_reshaped.shape)

Error:  shape '[1, 7]' is invalid for input of size 9


tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]])
torch.Size([1, 9])


tensor([[1., 2., 3.],
        [4., 5., 6.],
        [7., 8., 9.]])
torch.Size([3, 3])


In [ ]:
"""
Change the View
"""

z = x.view(1, 9)
print(z, z.shape)
print(x)

tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]) torch.Size([1, 9])
tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.])


In [ ]:
z[:, 0] = 5 # all rows and 5. column
z, x

(tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]]),
 tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.]))

In [ ]:
"""
Stack tensors on top of each other
"""

x_stacked = torch.stack([x, x, x, x], dim=1) # when dim = 0 size = (4, 9), when dim = 1 size = (9, 4)
x_stacked, x_stacked.shape

(tensor([[5., 5., 5., 5.],
         [2., 2., 2., 2.],
         [3., 3., 3., 3.],
         [4., 4., 4., 4.],
         [5., 5., 5., 5.],
         [6., 6., 6., 6.],
         [7., 7., 7., 7.],
         [8., 8., 8., 8.],
         [9., 9., 9., 9.]]),
 torch.Size([9, 4]))

In [ ]:
"""
Squezee - Removes all single dimensions from a target tensor
Unsqueeze - Adds a single dimension to a target tensor at a specific dim
"""
print(f"Previous tensor: {x_reshaped}")
print(f"Previous shape: {x_reshaped.shape}")

x_unsqueezed = x_reshaped.unsqueeze(dim=0)

print(f"\nNew Unsqueezed Tensor: {x_unsqueezed}")
print(f"New Unsqueezed Shape: {x_unsqueezed.shape}")

x_squeezed = x_reshaped.squeeze()

print(f"\nNew squeezed Tensor: {x_squeezed}")
print(f"New squeezed Shape: {x_squeezed.shape}")

Previous tensor: tensor([[5., 2., 3.],
        [4., 5., 6.],
        [7., 8., 9.]])
Previous shape: torch.Size([3, 3])

New Unsqueezed Tensor: tensor([[[5., 2., 3.],
         [4., 5., 6.],
         [7., 8., 9.]]])
New Unsqueezed Shape: torch.Size([1, 3, 3])

New squeezed Tensor: tensor([[5., 2., 3.],
        [4., 5., 6.],
        [7., 8., 9.]])
New squeezed Shape: torch.Size([3, 3])


In [ ]:
"""
torch.permute - rearranges the dimensions of a target tensor in a specified order
"""
x_original = torch.rand(size=(224, 224, 3)) # height, weight, color_channels

x_permuted = x_original.permute(2, 0, 1) # indexes: 0 -> 2 | 1 -> 0 | 2 -> 1, color_channels, height, width

x_original.shape, x_permuted.shape

(torch.Size([224, 224, 3]), torch.Size([3, 224, 224]))

### INDEXING (SELECTING DATA FROM TENSORS)

In [ ]:
t = torch.arange(1, 10).reshape(1, 3, 3)
t, t.shape

(tensor([[[1, 2, 3],
          [4, 5, 6],
          [7, 8, 9]]]),
 torch.Size([1, 3, 3]))

In [ ]:
t[0]

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [ ]:
t[0][1], t[0, 1]

(tensor([4, 5, 6]), tensor([4, 5, 6]))

In [ ]:
t[0, 1, 2], t[0][1][2]

(tensor(6), tensor(6))

In [ ]:
t[:, 0]

tensor([[1, 2, 3]])

In [ ]:
t[:, :, 2]

tensor([[3, 6, 9]])

In [ ]:
t[:, 0, 0], t[:][0][0][0]

(tensor([1]), tensor(1))

### PYTORCH TENSORS & NUMPY

In [ ]:
"""
NumPy to Tensor
"""
import numpy as np

array = np.arange(1., 8.)
np_tensor = torch.from_numpy(array)  # .type(torch.float32)
array, np_tensor

(array([1., 2., 3., 4., 5., 6., 7.]), tensor([1., 2., 3., 4., 5., 6., 7.]))

In [ ]:
array.dtype, np_tensor.dtype

(dtype('float64'), torch.float32)

In [ ]:
array = array + 1
array, np_tensor

(array([3., 4., 5., 6., 7., 8., 9.]), tensor([1., 2., 3., 4., 5., 6., 7.]))

In [ ]:
"""
Tensor to NumPy
"""
example_tensor = torch.ones(7)
tensor_to_np_array = example_tensor.numpy()
example_tensor, tensor_to_np_array

(tensor([1., 1., 1., 1., 1., 1., 1.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

### REPRODUCUBILITY (TRYING TO TAKE RANDOM OUT OF RANDOM)

In [ ]:
random_tensor_A = torch.rand(3, 4)
random_tensor_B = torch.rand(3, 4)

print(random_tensor_A)
print("\n", random_tensor_B)
print("\n", random_tensor_A == random_tensor_B)

tensor([[0.5008, 0.3382, 0.4858, 0.5767],
        [0.5029, 0.3443, 0.2482, 0.9120],
        [0.2601, 0.3189, 0.5522, 0.7457]])

 tensor([[0.2264, 0.1323, 0.0981, 0.0895],
        [0.3614, 0.8601, 0.1190, 0.1652],
        [0.1930, 0.7328, 0.7160, 0.9781]])

 tensor([[False, False, False, False],
        [False, False, False, False],
        [False, False, False, False]])


In [ ]:
"""
Let's make some random but reproducible tensors
"""

RANDOM_SEED = 42

torch.manual_seed(RANDOM_SEED)
random_tensor_C = torch.rand(3, 4)

torch.manual_seed(RANDOM_SEED)
random_tensor_D = torch.rand(3, 4)

print(random_tensor_C)
print("\n", random_tensor_D)
print("\n", random_tensor_D == random_tensor_C)

tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])

 tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])

 tensor([[True, True, True, True],
        [True, True, True, True],
        [True, True, True, True]])


### CHECK FOR GPU ACCESS WITH PYTORCH

In [ ]:
!nvidia-smi

Thu Oct 26 11:57:24 2023       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 525.105.17   Driver Version: 525.105.17   CUDA Version: 12.0     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  Tesla T4            Off  | 00000000:00:04.0 Off |                    0 |
| N/A   36C    P8     9W /  70W |      3MiB / 15360MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
                                                                               
+-------

In [ ]:
torch.cuda.is_available()

True

In [ ]:
"""
Setup device agnostic code
"""

device = "cuda" if torch.cuda.is_available() else "cpu"
device

'cuda'

In [ ]:
"""
Count number of devices
"""
torch.cuda.device_count()

1

In [ ]:
"""
Putting Tensors on the GPU
"""

tensorD = torch.tensor([1, 2, 3])  # default device = "cpu"

print(tensorD, tensorD.device)

tensor([1, 2, 3]) cpu


In [ ]:
"""
Move tensor to GPU if available
"""
tensor_on_gpu = tensorD.to(device)
tensor_on_gpu

tensor([1, 2, 3], device='cuda:0')

In [ ]:
"""
Move tensor to CPU
"""
tensor_on_gpu.numpy()  # Numpy does not work in gpu

TypeError: ignored

In [ ]:
"""
To fix the GPU tensor with NumPy issue
"""
tensor_back_on_cpu = tensor_on_gpu.cpu().numpy()
tensor_back_on_cpu,

(array([1, 2, 3]),)